firstapp/blog/urls.py
from django.conf.urls import patterns, include, url

from blog.views import PostListView, PostDetailView, like

urlpatterns = patterns('',
    url(r'^$', PostListView.as_view(), name='list'),
    url(r'^likes/$', like, name='like'),
    url(r'^post/(?P<pk>\d+)/$', PostDetailView.as_view(), name='detail'),
    url(r'^page/(?P<page>[0-9]+)/$', PostListView.as_view(), name='paginate_list'),
    url(r'^category/(?P<pk>\d+)/$', PostListView.as_view(categorised = True), name='Categorise_list'),
    url(r'^category/(?P<pk>\d+)/page/(?P<page>[0-9]+)/$', PostListView.as_view(categorised = True), name='list'),
)

firstapp/firstapp/firstapp/firstapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
]

firstapp/firstapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from registration.forms import RegistrationFormUniqueEmail
from registration.backends.default.views import RegistrationView

urlpatterns = [
    # Examples:
    # url(r'^$', 'firstapp.views.home', name='home'),
    url(r'^fridgeroom/', include('fridgeroom.urls', namespace="room")),
    url(r'^novels/', include('novels.urls', namespace="novels")),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^polls/', include('polls.urls', namespace="polls")),	
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/register/$', RegistrationView.as_view(form_class=RegistrationFormUniqueEmail), name='registration_register'),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^comments/', include('django_comments.urls')),
]

firstapp/mtg/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('',
    url(r'^$', MtgListView.as_view(), name='index'),
)

firstapp/novels/urls.py
from django.conf.urls import patterns, include, url

from novels.views import MainListView, MainDetailView, subscribe_to, IndexView, download_issue_archive, ReadOnlineView 
from novels.models import Group, Character, Publisher, Arc, Title, Issue, Strip

urlpatterns = patterns('',
#Index:
    url(r'^$', IndexView.as_view(), name='index'),
#Publisher:    
    url(r'^publishers/$', MainListView.as_view(model = Publisher, template_name = "novels/pub_list.html"), name='PublisherList'),
    url(r'^publishers/(?P<slug>[\w-]+)/$', MainDetailView.as_view(model = Publisher, template_name = "novels/pub_detail.html"), name='PublisherDetail'),
    url(r'^subscribe/publisher/$', subscribe_to, {'mod': Publisher}, name='Sub_to_Pub'),
#Title:                       
    url(r'^titles/$', MainListView.as_view(model = Title, template_name = "novels/tit_list.html"), name='TitleList'),
    url(r'^titles/(?P<slug>[\w-]+)/$', MainDetailView.as_view(model = Title, template_name = "novels/tit_detail.html"), name='TitleDetail'),
    url(r'^subscribe/title/$', subscribe_to, {'mod': Title}, name='Sub_to_Title'),
#Arc:
    url(r'^arcs/$', MainListView.as_view(model = Arc, template_name = "novels/arc_list.html"), name='ArcList'),
    url(r'^arcs/(?P<slug>[\w-]+)/$', MainDetailView.as_view(model = Arc, template_name = "novels/arc_detail.html"), name='ArcDetail'),
    url(r'^subscribe/arc/$', subscribe_to, {'mod': Arc}, name='Sub_to_Arc'),
#Issue
    url(r'^titles/issue/(?P<slug>[\w-]+)/$', MainDetailView.as_view(model = Issue, template_name = "novels/issue_detail.html"), name='IssueDetail'),
    url(r'^download/issue/(?P<pk>\d+)/$', download_issue_archive, name='Download_Issue'),
#Group:
    url(r'^groups/$', MainListView.as_view(model = Group, template_name = "novels/group_list.html"), name='GroupList'),
    url(r'^groups/(?P<slug>[\w-]+)/$', MainDetailView.as_view(model = Group, template_name = "novels/group_detail.html"), name='GroupDetail'),
    url(r'^subscribe/group/$', subscribe_to, {'mod': Group}, name='Sub_to_Group'),
#Character:
    url(r'^chars/$', MainListView.as_view(model = Character, template_name = "novels/char_list.html"), name='CharList'),
    url(r'^chars/(?P<slug>[\w-]+)/$', MainDetailView.as_view(model = Character, template_name = "novels/char_detail.html"), name='CharDetail'),
    url(r'^subscribe/char/$', subscribe_to, {'mod': Character}, name='Sub_to_Char'),
#OnlineReading
    url(r'^read/(?P<title_slug>[\w-]+)/(?P<issue_slug>[\w-]+)/(?P<page>[0-9]+)/$', ReadOnlineView.as_view(model = Strip, template_name = "novels/read_strip.html"), name='ReadStrip'),
    )

firstapp/blog/models.py
from django.db import models
import datetime
import random
import string
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.template.defaultfilters import slugify

class Category(models.Model):
    name = models.CharField(max_length=20, unique=True)
    desc = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('blog:Categorise_list', args=[self.id])

class Post(models.Model):
    title = models.CharField(max_length=255)
    datetime = models.DateTimeField(default=datetime.datetime.now, verbose_name=u"Publication date")
    content = models.TextField(max_length=10000)
    cat = models.ForeignKey(Category, null=True, on_delete=models.SET_NULL)   
    author = models.ForeignKey(User, null=True)
    imgURL = models.CharField(max_length=255, default="http://placehold.it/200x140")
    tags = models.CharField(max_length=50, null=True, blank=True)
    slug = models.SlugField(default=slugify(''.join(random.sample(string.ascii_lowercase, 10))))
    likes = models.ManyToManyField(User, related_name = 'likes')

    def __str__(self):
        return self.title
    
    def tags_list(self):
        return self.tags.split(";")

    def get_absolute_url(self):
        return reverse('blog:detail', args=[self.id])
    
    def get_likes_count(self):
        return self.likes.count()
    
    def get_descr_of_post(self):
        descr = self.content[:350] + ' ...'        
        return descr
    
    def save(self, *args, **kwargs):
        if slugify(self.title) != '':
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

firstapp/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.core import serializers
from django.views.generic import ListView, DetailView
from blog.models import Post, Category
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
import json

class PostListView(ListView):
    model = Post 
    paginate_by=5
    categorised = False
    
    def get_context_data(self, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)
        categorised = self.categorised
        context['categorised'] = categorised
        if categorised:
            context['cat_id'] = self.kwargs['pk']
        return context
    
    def get_queryset(self):
        if self.categorised:
            self.category = get_object_or_404(Category, id=self.kwargs['pk'])
            qset = Post.objects.filter(cat__id=self.category.id).order_by('-datetime')
        else:
            qset = Post.objects.order_by('-datetime')            
        return qset 

class PostDetailView(DetailView):
    model = Post
    
    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        post = super(PostDetailView, self).get_object()
        user = self.request.user
        liked = post.likes.filter(id=user.id).exists()
        context['liked'] = liked
        return context
    
@login_required
@require_POST
def like(request):
    if request.method == 'POST':
        user = request.user
        slug = request.POST.get('slug', None)
        post = get_object_or_404(Post, slug=slug)
        
        if post.likes.filter(id=user.id).exists():
            post.likes.remove(user)
            message = 'You disliked this post'
            liked = False
        else:
            post.likes.add(user)
            message = 'You liked this post'
            liked = True
            
    data = json.dumps({'likes_count': post.get_likes_count(), 'message': message, 'liked': liked})
    return HttpResponse(data, content_type='application/json')
    

firstapp/blog/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ru">
<head>
{% include "blog/head.html" %}
<script type="text/javascript">
        $(function(){
        {% block jquery %}
        {% endblock %}
        });
</script>
</head>
<body>
{% include "blog/nav.html" %}
<div class="container">
	<div class="row">
		<div class="col-md-8"><!-- maincontainer -->
     			{% block content %}Empty page{% endblock %}
                {% if is_paginated %}
                    <div class="text-center">
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                            <li>
                                <a href="/blog/{% if categorised %}category/{{ cat_id }}/{% endif %}page/{{ page_obj.previous_page_number }}" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                            {% else %}
                            <li class="disabled">
                                <a href="#" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                            {% endif %}
                            {% for i in page_obj.paginator.page_range %}
                                {% if forloop.counter == page_obj.number %}
                                <li class="active"><a href="#">{{ forloop.counter }}<span class="sr-only">(current)</span></a></li>
                                {% else %}
                                <li><a href="/blog/{% if categorised %}category/{{ cat_id }}/{% endif %}page/{{ forloop.counter }}">{{ forloop.counter }}</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if page_obj.has_next %}
                            <li>
                                <a href="/blog/{% if categorised %}category/{{ cat_id }}/{% endif %}page/{{ page_obj.next_page_number }}" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                            {% else %}
                            <li class="disabled">
                                <a href="#" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                {% endif %}
		</div>
		<div class="col-md-4"><!-- sidebar -->
            <div class="container-fluid">
                <div class="row">

                    <div class="panel panel-default">
                       {% if user.is_authenticated %}
                       <div class="panel-body">
                         <img class="img-rounded" style="width: 64px; height: 64px" src="{{ user.userprofile.avatar }}" alt="img">
                           <strong> Вы авторизованы как: {{ user.username }}</strong></br>
                           <a href="{% url 'auth_logout' %}">(Выйти)</a>
                       </div>
                       {% else %}
                       <div class="panel-heading"><div class="panel-title"><strong>Авторизация</strong></div></div>
                        <div class="panel-body">
                                <form method="post" action="{% url 'auth_login' %}" role="form">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Логин</label>
                                    <input type="text" id="id_username" name="username" class="form-control" id="exampleInputEmail1" placeholder="Введите ваш логин">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Пароль <a href="{% url 'auth_password_reset' %}">(забыли пароль?)</a></label>
                                    <div class="input-group">
                                        <input type="password" id="id_password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Введите ваш пароль">
                                            <span class="input-group-btn">
                                                <button type="submit"  class="btn btn-default" type="button">Войти <i class="glyphicon glyphicon-log-in"></i></button>
                                            </span>
                                    </div>
                                </div>
                                <input type="hidden" name="next" value="{{ next }}" />
                            </form>

</div>
                   <div class="panel-footer"><a class="btn btn-default btn-block" href="{% url 'registration_register' %}">Регистрация</a></div>
                   {% endif %}
                    </div>
                    {% include "blog/tweetBoard.html" %}
                </div>
            </div>
        </div>
    </div><!-- row -->
</div> <!-- container -->

</body>
</html>

firstapp/blog/templates/blog/base_auth.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ru">
<head>
{% include "blog/head.html" %}
<script type="text/javascript">
        $(function(){
        {% block jquery %}
        {% endblock %}
        });
</script>
</head>
<body>
{% include "blog/nav.html" %}
<div class="container">
	<div class="row">
		<!-- maincontainer -->
       <div class="container-fluid">
        <div class="panel panel-default">
                       <div class="panel-body">
                       {% if user.is_authenticated %}
                           <img class="img-rounded" style="width: 64px; height: 64px" src="{{ user.userprofile.avatar }}" alt="img">
                           <strong> Вы авторизованы как: {{ user.username }} </strong>
                           <a href="{% url 'auth_logout' %}">(Выйти)</a>

                       {% else %}
     			{% block auth_block %}{% endblock %}
     			{% endif %}
     			</div>
        </div>
        </div>
    </div><!-- row -->
</div> <!-- container -->

</body>
</html>

firstapp/blog/templates/blog/head.html
{% load staticfiles %}
        <meta charset="utf-8" />
        <title>OpenFridge</title>
        <link href="{% static 'blog/css/bootstrap(def).css' %}" rel="stylesheet">
        <style>
            body {
                padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
            }
        </style>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <script src="{% static 'blog/js/bootstrap.js' %}" type="text/javascript"></script>

firstapp/blog/templates/blog/nav.html
{% load extra_tags %}
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'blog:list' %}">OPEN|Fridge</a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse">
            
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Категории<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                    {% get_list %}    
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Комиксы<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'novels:index' %}">Обновления</a></li>
                        <li><a href="{% url 'novels:PublisherList' %}">Издатели</a></li>
                        <li><a href="{% url 'novels:TitleList' %}">Серии</a></li>
                        <li><a href="{% url 'novels:ArcList' %}">События</a></li>
                        <li><a href="{% url 'novels:GroupList' %}">Команды</a></li>
                        <li><a href="{% url 'novels:CharList' %}">Персонажи</a></li>
                    </ul>
                </li>
            </ul>
        
        <form class="navbar-form navbar-right" role="search">
    
                    
                <div class="input-group">
                    <input type="text" class="form-control">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                    </span>
                </div>
        
        </form>            
        </div>
    </div>
</nav>

firstapp/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load comments %}
{% block jquery %}
     $('[data-toggle="tooltip"]').tooltip();

    $('#like').click(function(){
      $.ajax({
               type: "POST",
               url: "{% url 'blog:like' %}",
               data: {'slug': $(this).attr('name'), 'csrfmiddlewaretoken': '{{ csrf_token }}'},
               dataType: "json",
               success: function(response) {
                      console.log(response.message);
                      console.log('Post likes count is now ' + response.likes_count);
                      console.log(response.liked);
                      $('#like').toggleClass("active btn-primary",response.liked);
                      $('#like').toggleClass("btn-default",!response.liked);
                      if (response.liked){
                         $('#like').html("<i class='glyphicon glyphicon-heart'></i> Нравится <span class='badge'>" + response.likes_count + "</span>");
                        }else{
                          $('#like').html("<i class='glyphicon glyphicon-heart-empty'></i> Нравится <span class='badge'>" + response.likes_count + "</span>");
                        }
                },
                error: function(rs, e) {
                       console.log(rs.responseText);
                }
          });
    })
{% endblock %}
{% block content %}
<h3>{{ post.title }} <p><small><i class="glyphicon glyphicon-user"></i> {{ post.author }} | <i class="glyphicon glyphicon-calendar"></i> {{ post.datetime|date:"j N" }} | <i class="glyphicon glyphicon-time"></i> {{ post.datetime|date:"G:i" }}</small></p></h3>
    <div class="well container-fluid">{{ post.content }}</div>
    {% if user.is_authenticated %}
    <button class="{% if liked %} active btn-primary {% endif %}btn{% if not liked %} btn-default{% endif %}" type="button" id="like" name="{{ post.slug }}" value="Like">
        <i class="glyphicon glyphicon-heart{% if not liked %}-empty{% endif %}"></i> Нравится <span class="badge">{{ post.get_likes_count }}</span>
    </button>
    {% endif %}
    <hr>
    {% get_comment_count for post as comment_count %}
    <p><i class="glyphicon glyphicon-comment"></i> {{ comment_count }} коммент. </p>
    {% if user.is_authenticated %}
        {% get_comment_form for post as form %}
        <form action="{% comment_form_target %}" method="post">
            {% csrf_token %}
            <fieldset>
                <div class="form-group">
                    <textarea class="form-control" name="comment" id="id_comment" maxlength="3000" rows="3"></textarea>
                </div>
                <input id="id_honeypot" style="display: none;" name="honeypot" type="text">
                    {{ form.content_type }}
                    {{ form.object_pk }}
                    {{ form.timestamp }}
                    {{ form.security_hash }}
                <div class="pull-right form-group">
                   <div class="btn-group">
                        <button type="submit" name="submit" class="btn btn-default">Отправить</button>
                        <button type="submit" name="preview" class="btn btn-default">Предпросмотр</button>
                    </div>
                </div>
            </fieldset>
        </form>
    {% else %}
    <div class="alert alert-warning">
        <strong>Пожалуйста <a href="{% url 'auth_login' %}" class="btn btn-default btn-sm">авторизуйтесь</a> или <a href="{% url 'registration_register' %}" class="btn btn-default btn-sm">зарегистрируйтесь</a> , чтобы комментировать данную статью.</strong>
    </div>
    {% endif %}
    {% get_comment_list for post as comment_list %}
    {% for comment in comment_list %}
       <div class="media">
          <a name="c{{ comment.id }}"></a>
            <a class="pull-left">
                <img class="media-object img-rounded" style="width: 64px; height: 64px" src="{{ comment.user.userprofile.avatar }}" alt="img">
            </a>
            <div class="media-body">
               <div class="panel panel-default">
               <div class="panel-heading">
                   <h4 class="panel-title"><strong>{{ comment.user_name }}</strong> <small>{{ comment.submit_date }}</small>
                   <a href="http://{{ request.META.HTTP_HOST }}{% get_comment_permalink comment %}" class="pull-right" >
                               <i class="glyphicon glyphicon-link"></i>
                    </a>
                    </h4>
                </div>
                <div class="panel-body">
                <p>{{ comment.comment }}</p>
                </div>
            </div>
       </div>
       </div>
    {% endfor %}
{% endblock %}

firstapp/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% load comments %}
{% block content %}
    {% for post in object_list %}
    {% get_comment_count for post as comment_count %}
    <div class="post content">
	<div>
		<div class="panel panel-default">
            <div class="panel-heading">      
                        <strong>{{ post.title }}</strong>                
                        <span class="showPic hidden-sm hidden-md hidden-lg pull-right">
                            <a data-toggle="modal" data-target=".modalPic-{{ post.id }}"><i class="glyphicon glyphicon-picture"></i></a>                    
                        </span> 
                    <div class="modal fade modalPic-{{ post.id }}" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-sm">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                                        <h4 class="modal-title" id="mySmallModalLabel">Изображение<a class="anchorjs-link" href="#mySmallModalLabel"><span class="anchorjs-icon"></span></a></h4>
                                </div>
                                <div class="modal-body text-center">
                                    <img src="{{ post.imgURL }}" style="width: 200px; height: 140px;" alt="">
                                </div>
                            </div>
                        </div>
                    </div>            
                    <div class="clearfix"></div>   
            </div>
                       
            <ul class="list-group">
                <li class="list-group-item">
                       <div class="col-md-6 col-sm-6 col-xs-6">
                       <div class="row">
                        <i class="glyphicon glyphicon-user"></i><span> {{ post.author }} </span>                        
                        <i class="glyphicon glyphicon-comment"></i><span> {{ comment_count }} </span>
                        <i class="glyphicon glyphicon-heart"></i><span> {{ post.get_likes_count }} </span>
                        </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                        <div class="row">
                        <span class="pull-right">
                        <i class="glyphicon glyphicon-calendar"></i><span> {{ post.datetime|date:"j N" }} </span>
                        <i class="glyphicon glyphicon-time"></i><span> {{ post.datetime|date:"G:i" }} </span>
                       </span>
                       </div>
                       </div>
                       <div class="clearfix"></div>
                </li>
            </ul>
			<div class="panel-body">
            <div class="media-left hidden-xs">
                    <img class="media-object img-rounded" src="{{ post.imgURL }}" alt="{{ post.title }}">                  
            </div>
            <div class="media-body">
			<div class="caption">
				<p>{{ post.get_descr_of_post }}</p>
			</div>
            </div>
			</div>
			<div class="panel-footer">
				<div class="col-xs-9 col-sm-9 col-md-9 col-lg-9">
					<div class="row">
						<i class="glyphicon glyphicon-folder-open"></i>  &nbsp;<span class="label label-default">{{ post.cat }}</span>
                        <i class="glyphicon glyphicon-tags"></i>
                        {% for tag in post.tags_list %}
                          {% if forloop.counter == 1 %}
                              &nbsp;<span class="label label-primary">{{ tag }}</span>                          
                          {% else %}
                              &nbsp;<span class="label hidden-xs label-primary">{{ tag }}</span>
                          {% endif %}
                          
                        {% endfor %}
                        
					</div>
				</div>
				<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
				        <div class="row">
				            <a href="{{ post.get_absolute_url }}" class="btn btn-primary btn-xs pull-right" role="button">Читать <i class="glyphicon glyphicon-menu-hamburger"></i></a>
				        </div>					
					</div>
					<div class="clearfix"></div>
			</div>
		</div>	
	</div>
	<hr>
     </div>
    {% empty %}
    <div class="well well-lg">    
        <p><strong>В настоящий момент новости отсутствуют.</strong></p>
    </div>
    {% endfor %}
{% endblock %}

firstapp/blog/templates/blog/tweetBoard.html
<div class="panel panel-default">
    <div class="panel-body">
<a class="twitter-timeline" data-chrome="nofooter noborders transparent noscrollbar" height="400" href="https://twitter.com/SquareFridge" data-widget-id="612874633625382912">Твиты от @SquareFridge</a>
<script>
    !function(d,s,id){
        var js,fjs=d.getElementsByTagName(s)[0],
            p=/^http:/.test(d.location)?'http':'https';
        if(!d.getElementById(id)){
            js=d.createElement(s);
            js.id=id;
            js.src=p+"://platform.twitter.com/widgets.js";
            fjs.parentNode.insertBefore(js,fjs);
        }
    }(document,"script","twitter-wjs");
</script>
</div>
</div>