firstapp/blog/urls.py
from django.conf.urls import patterns, include, url

from blog.views import PostListView, PostDetailView, like

urlpatterns = patterns('',
    url(r'^$', PostListView.as_view(), name='list'),
    url(r'^likes/$', like, name='like'),
    url(r'^post/(?P<pk>\d+)/$', PostDetailView.as_view(), name='detail'),
    url(r'^page/(?P<page>[0-9]+)/$', PostListView.as_view(), name='paginate_list'),
    url(r'^category/(?P<pk>\d+)/$', PostListView.as_view(categorised = True), name='Categorise_list'),
    url(r'^category/(?P<pk>\d+)/page/(?P<page>[0-9]+)/$', PostListView.as_view(categorised = True), name='list'),
)

firstapp/firstapp/firstapp/firstapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
]

firstapp/firstapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from registration.forms import RegistrationFormUniqueEmail
from registration.backends.default.views import RegistrationView

urlpatterns = [
    # Examples:
    # url(r'^$', 'firstapp.views.home', name='home'),
    url(r'^fridgeroom/', include('fridgeroom.urls', namespace="room")),
    url(r'^novels/', include('novels.urls', namespace="novels")),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^polls/', include('polls.urls', namespace="polls")),	
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/register/$', RegistrationView.as_view(form_class=RegistrationFormUniqueEmail), name='registration_register'),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^comments/', include('django_comments.urls')),
]

firstapp/mtg/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('',
    url(r'^$', MtgListView.as_view(), name='index'),
)

firstapp/novels/urls.py
from django.conf.urls import patterns, include, url

from novels.views import MainListView, MainDetailView, subscribe_to, IndexView, download_issue_archive, ReadOnlineView 
from novels.models import Group, Character, Publisher, Arc, Title, Issue, Strip

urlpatterns = patterns('',
#Index:
    url(r'^$', IndexView.as_view(), name='index'),
#Publisher:    
    url(r'^publishers/$', MainListView.as_view(model = Publisher, template_name = "novels/pub_list.html"), name='PublisherList'),
    url(r'^publishers/(?P<slug>[\w-]+)/$', MainDetailView.as_view(model = Publisher, template_name = "novels/pub_detail.html"), name='PublisherDetail'),
    url(r'^subscribe/publisher/$', subscribe_to, {'mod': Publisher}, name='Sub_to_Pub'),
#Title:                       
    url(r'^titles/$', MainListView.as_view(model = Title, template_name = "novels/tit_list.html"), name='TitleList'),
    url(r'^titles/(?P<slug>[\w-]+)/$', MainDetailView.as_view(model = Title, template_name = "novels/tit_detail.html"), name='TitleDetail'),
    url(r'^subscribe/title/$', subscribe_to, {'mod': Title}, name='Sub_to_Title'),
#Arc:
    url(r'^arcs/$', MainListView.as_view(model = Arc, template_name = "novels/arc_list.html"), name='ArcList'),
    url(r'^arcs/(?P<slug>[\w-]+)/$', MainDetailView.as_view(model = Arc, template_name = "novels/arc_detail.html"), name='ArcDetail'),
    url(r'^subscribe/arc/$', subscribe_to, {'mod': Arc}, name='Sub_to_Arc'),
#Issue
    url(r'^titles/issue/(?P<slug>[\w-]+)/$', MainDetailView.as_view(model = Issue, template_name = "novels/issue_detail.html"), name='IssueDetail'),
    url(r'^download/issue/(?P<pk>\d+)/$', download_issue_archive, name='Download_Issue'),
#Group:
    url(r'^groups/$', MainListView.as_view(model = Group, template_name = "novels/group_list.html"), name='GroupList'),
    url(r'^groups/(?P<slug>[\w-]+)/$', MainDetailView.as_view(model = Group, template_name = "novels/group_detail.html"), name='GroupDetail'),
    url(r'^subscribe/group/$', subscribe_to, {'mod': Group}, name='Sub_to_Group'),
#Character:
    url(r'^chars/$', MainListView.as_view(model = Character, template_name = "novels/char_list.html"), name='CharList'),
    url(r'^chars/(?P<slug>[\w-]+)/$', MainDetailView.as_view(model = Character, template_name = "novels/char_detail.html"), name='CharDetail'),
    url(r'^subscribe/char/$', subscribe_to, {'mod': Character}, name='Sub_to_Char'),
#OnlineReading
    url(r'^read/(?P<title_slug>[\w-]+)/(?P<issue_slug>[\w-]+)/(?P<page>[0-9]+)/$', ReadOnlineView.as_view(model = Strip, template_name = "novels/read_strip.html"), name='ReadStrip'),
    )

firstapp/novels/models.py
from django.db import models

from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.db.models.signals import pre_delete, post_save
from django.dispatch.dispatcher import receiver
from django.core.files import File
import datetime
import shutil
import rarfile
import os
import glob

YEAR_CHOICES = []
for r in range(1980, (datetime.datetime.now().year+1)):
    YEAR_CHOICES.append((r,r))
    
STATUS_CHOICES = []
STATUS_CHOICES.append(('Завершен','Completed'))
STATUS_CHOICES.append(('Незавершен','Ongoing'))

rarfile.UNRAR_TOOL = 'rar'



class Publisher(models.Model):
    pub_title = models.CharField(max_length = 255)
    found = models.IntegerField(choices=YEAR_CHOICES, default=datetime.datetime.now().year)
    twitter = models.URLField(verbose_name = u"Twitter")
    website = models.URLField(verbose_name = u"Website")
    imgUrl = models.URLField(default="http://placehold.it/150x150",verbose_name = u"Image")
    abbrev = models.CharField(max_length = 100)
    country = models.CharField(max_length = 100)
    desc = models.TextField(max_length = 1000)
    slug = models.SlugField(max_length = 255,blank=True)
    subs = models.ManyToManyField(User, related_name = 'Subscribers', blank=True)
    imprint_of = models.ForeignKey('Publisher',null=True, on_delete=models.SET_NULL, blank=True)
    
    def get_subs_count(self):
        return self.subs.count()
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.pub_title)
        super(Publisher, self).save(*args, **kwargs)
        
    def __str__(self):
        return self.pub_title
    
    def get_short_desc(self):
        return self.desc[:100]
    
    class Meta:
        ordering = ('found',)

class Group(models.Model):
    title = models.CharField(max_length = 255)
    orig_title = models.CharField(max_length = 255)
    publisher = models.ForeignKey(Publisher,null=True, on_delete=models.SET_NULL)
    desc = models.TextField(max_length = 1000)
    date = models.DateField(verbose_name = u"Creation date")
    slug = models.SlugField(max_length = 255,blank=True)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.orig_title)
        super(Group, self).save(*args, **kwargs)
        
    def __str__(self):
        return self.title    
    
class Arc(models.Model):
    arc_title = models.CharField(max_length = 255)
    orig_arc_title = models.CharField(max_length = 255)
    publisher = models.ForeignKey(Publisher,null=True, on_delete=models.SET_NULL)
    desc = models.TextField(max_length = 1000)    
    slug = models.SlugField(max_length = 255,blank=True)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.orig_arc_title)
        super(Arc, self).save(*args, **kwargs)
        
    def __str__(self):
        return self.arc_title
    
class Genre(models.Model):
    name = models.CharField(max_length = 255)
    
    def __str__(self):
        return self.name
        
class Title(models.Model):
    title = models.CharField(max_length = 255)
    orig_title = models.CharField(max_length = 255)
    publisher = models.ForeignKey(Publisher,null=True, on_delete=models.SET_NULL)
    imgUrl = models.URLField(default="http://placehold.it/155x235",verbose_name = u"Image")
    translateURL = models.URLField(default="http://",verbose_name = u"Trans")
    arc = models.ForeignKey(Arc,null=True, on_delete=models.SET_NULL,blank=True)
    author = models.CharField(max_length = 255, blank=True)
    artist = models.CharField(max_length = 255, blank = True)
    genre = models.ManyToManyField(Genre, related_name = 'Genre', blank = True)
    status = models.CharField(max_length = 255,choices = STATUS_CHOICES, default=STATUS_CHOICES[0])
    desc = models.TextField(max_length = 1000)
    date = models.DateField(verbose_name = u"Publication date")
    slug = models.SlugField(max_length = 255,blank=True)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.orig_title)
        super(Title, self).save(*args, **kwargs)
        
    def __str__(self):
        return self.title
    
class Character(models.Model):
    name = models.CharField(max_length = 255)
    real_name = models.CharField(max_length = 255)
    desc = models.TextField(max_length = 1000)
    publisher = models.ForeignKey(Publisher,null=True, on_delete=models.SET_NULL)
    groups = models.ManyToManyField(Group,related_name = "Groups")
    firstIssue = models.ForeignKey('Issue',null=True, on_delete=models.SET_NULL)
    slug = models.SlugField(max_length = 255,blank=True)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Character, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.name
    
class Issue(models.Model):
    number = models.PositiveIntegerField(null=True)
    trans_name = models.CharField(max_length = 255,blank=True,null=True)
    name = models.CharField(max_length = 255,blank=True,null=True)
    date = models.DateField(verbose_name = u"Publication date")
    publisher = models.ForeignKey(Publisher,null=True, on_delete=models.SET_NULL)
    arc = models.ForeignKey(Arc,null=True, on_delete=models.SET_NULL, blank = True)
    archive = models.FileField(blank=True)
    groups = models.ManyToManyField(Group,related_name = "IssueGroups",blank=True)
    characters = models.ManyToManyField(Character,related_name = "Chars",blank=True)
    tit = models.ForeignKey(Title, null=True, on_delete=models.SET_NULL)
    slug = models.SlugField(max_length = 255,blank=True)
    pub_datetime = models.DateTimeField(auto_now_add=True)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.tit.slug+'-'+str(self.number))
        for field in self._meta.fields:
            if field.name == 'archive':
                field.upload_to = 'novels/static/novels/comics/%s/%s/%s' % (self.publisher.slug, self.tit.slug, self.number)
        super(Issue, self).save(*args, **kwargs)        
        
    def __str__(self):
        return self.tit.orig_title + "-" + str(self.number)

class Strip(models.Model):
    num = models.PositiveIntegerField(null=True)
    issue = models.ForeignKey(Issue,null=True, on_delete=models.SET_NULL)
    img_file_name = models.CharField(max_length = 50)
    slug = models.SlugField(max_length = 255,blank=True,primary_key=True)
    
    def save(self, *args, **kwargs):
        s = self.issue.tit.slug+'-'+str(self.issue.number)+'-'+str(self.num)
        self.slug = slugify(s)
        super(Strip, self).save(*args, **kwargs)
        
    def __str__(self):
        return self.issue.tit.slug+'-'+str(self.issue.number)+'-'+str(self.num)
    
    def get_abs_url(self):
        return '/static/novels/comics/' + self.issue.tit.publisher.slug + '/' + self.issue.tit.slug + '/' + str(self.issue.number) + '/img/' + self.img_file_name
    
    
@receiver(pre_delete, sender=Issue)
def Issue_before_delete(sender, instance, **kwargs):
    name = instance.archive.path.split('/')[-1]
    path = instance.archive.path.replace(name,'')
    try:
        shutil.rmtree(path)
    except FileNotFoundError:
        print('No such directory: '+path)
    instance.archive.delete(False)
    Strip.objects.filter(issue=instance).delete()
    
@receiver(post_save, sender=Issue)
def Issue_after_save(sender, instance, **kwargs):
    arch = rarfile.RarFile(instance.archive.path, 'r')
    name = instance.archive.path.split('/')[-1]
    path = instance.archive.path.replace(name,'')+'img/'
    arch.extractall(path)
    os.chdir(path)
    a = []
    for file in glob.glob("*.jpg"):
        a.append(file)
    a.sort()
    for idx, strip in enumerate(a):
        reopen = open(path+strip, "rb")
        dj_file = File(reopen)
        new_strip = Strip(num=idx, issue=instance, img_file_name=strip)
        new_strip.save()
        
        
        
        
    

    
    
    

    
    
    
    
    

firstapp/novels/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, TemplateView
from novels.models import Group, Character, Publisher, Arc, Title, Issue, Strip
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.utils.encoding import smart_str
import json
from django.http import HttpResponse
from datetime import datetime, timedelta

class MainListView(ListView):
    ''' empty '''
        
class ReadOnlineView(ListView):
    paginate_by = 1
    
    def get_context_data(self, **kwargs):
        context = super(ReadOnlineView, self).get_context_data(**kwargs)
        issue = get_object_or_404(Issue, tit__slug = self.kwargs['title_slug'], slug=self.kwargs['issue_slug'])
        total_strip = Strip.objects.filter(issue=issue).count()
        progress = round((int(self.kwargs['page']) * 100)/total_strip)
        context['progress'] = progress
        context['issue'] = issue
        return context
        
    def get_queryset(self):
        obj = get_object_or_404(Issue, tit__slug = self.kwargs['title_slug'], slug=self.kwargs['issue_slug'])
        qset = Strip.objects.filter(issue=obj).order_by('num')
        return qset
    
    
class MainDetailView(DetailView):
    
    def get_context_data(self, **kwargs):
        context = super(MainDetailView, self).get_context_data(**kwargs)
        obj = super(MainDetailView, self).get_object()
        user = self.request.user
        if self.model == Publisher:
            subed = obj.subs.filter(id=user.id).exists()
            context['subed'] = subed
        if self.model == Title:
            issues = Issue.objects.filter(tit=obj)
            
            thumbnails = []
            for issue in issues:
                thumbnails.append(Strip.objects.get(issue=issue,num=0))
                
            context['issues'] = issues
            context['thumbnails'] = thumbnails
            context['num_of_issue'] = issues.count()
        if self.model == Issue:
            strips_count = Strip.objects.filter(issue=obj).count()
            strips = Strip.objects.filter(issue=obj).order_by('num')[:7]
            context['strips'] = strips
            context['strips_count'] = strips_count
        return context
    
class IndexView(TemplateView):
    template_name = "novels/index.html"
    
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        last_issues = Issue.objects.order_by('-pub_datetime')[:14]
        unsort_pubs = Publisher.objects.all()
        sort_pubs = sorted(unsort_pubs, key= lambda t: t.subs.count(), reverse=True)
        top_pubs = sort_pubs[:6]
        
        thumbnails = []
        titles = []
        for issue in last_issues:
            thumbnails.append(Strip.objects.get(issue=issue,num=0))
            if not(issue.tit in titles):
                titles.append(issue.tit)
        
        context['thumbnails'] = thumbnails
        context['last_issues'] = last_issues
        context['top_pubs'] = top_pubs
        context['titles'] = titles
        return context

@login_required
@require_POST    
def subscribe_to(request, mod):
    if request.method == 'POST':
        user = request.user
        slug = request.POST.get('slug', None)
        obj = get_object_or_404(mod, slug=slug)
        
        if obj.subs.filter(id=user.id).exists():
            obj.subs.remove(user)
            message = 'You described from updates'
            subscribe = False
        else:
            obj.subs.add(user)
            message = 'You subscribe to updates'
            subscribe = True
            
    data = json.dumps({'subs_count': obj.get_subs_count(), 'message': message, 'subscribe': subscribe})
    return HttpResponse(data, content_type='application/json')

def download_issue_archive(request, pk):
    issue = get_object_or_404(Issue, id=pk)
    path = issue.archive.path
    name = path.split('/')[-1]

    response = HttpResponse(content_type='application/force-download')
    response['Content-Disposition'] = 'attachment; filename=%s' % smart_str(name)
    response['X-Sendfile'] = smart_str(path)
    return response

firstapp/novels/templates/novels/arc_list.html
{% extends 'novels/base.html' %}
{% block content %}
<div class="container">
<div class="row">
 {% for publisher in object_list %}
 <div class="col-xs-6 col-sm-3 col-md-3 col-lg-2">
  <div class="thumbnail" style="height: 220px;">
          <a href="{% url 'novels:PublisherDetail' publisher.slug %}"><img class="img-rounded" src="{{ publisher.imgUrl }}" style="width: 150px; height: 150px;" alt="{{ publisher.pub_title }} Picture"></a>
      <div class="caption text-center">
          <strong>{{ publisher.pub_title }}</strong>
          <p>{{ publisher.found|date:"Y" }} г.</p>
    </div>
  </div>
  </div>
  {% endfor %}
</div>
</div>
{% endblock %}

firstapp/novels/templates/novels/group_list.html
{% extends 'novels/base.html' %}
{% block content %}
<div class="container">
<div class="row">
 {% for publisher in object_list %}
 <div class="col-xs-6 col-sm-3 col-md-3 col-lg-2">
  <div class="thumbnail" style="height: 220px;">
          <a href="{% url 'novels:PublisherDetail' publisher.slug %}"><img class="img-rounded" src="{{ publisher.imgUrl }}" style="width: 150px; height: 150px;" alt="{{ publisher.pub_title }} Picture"></a>
      <div class="caption text-center">
          <strong>{{ publisher.pub_title }}</strong>
          <p>{{ publisher.found|date:"Y" }} г.</p>
    </div>
  </div>
  </div>
  {% endfor %}
</div>
</div>
{% endblock %}

firstapp/novels/templates/novels/index.html
{% extends 'novels/base.html' %}
{% block jquery %}
    $(document).ready(function() {
    
        $('.slick-crousel').slick({
            slidesToShow: 6,
            slidesToScroll: 1,
            infinite: true,
            autoplay: true,
            autoplaySpeed: 5000,
            arrows: false,
            responsive: [
               {
                  breakpoint: 1200,
                  settings: {
                    slidesToShow: 5,
                    slidesToScroll: 1,
                  }
                },
                {
                  breakpoint: 992,
                  settings: {
                    slidesToShow: 4,
                    slidesToScroll: 1,
                  }
                },
                {
                  breakpoint: 768,
                  settings: {
                    slidesToShow: 3,
                    slidesToScroll: 1,
                  }
                },
                {
                  breakpoint: 510,
                  settings: {
                    slidesToShow: 2,
                    slidesToScroll: 1,
                  }
                },
                {
                  breakpoint: 380,
                  settings: {
                    slidesToShow: 1,
                    slidesToScroll: 1,
                  }
                }
          ]                                  
        });    
    
    });
{% endblock %}
{% block content %}       
       <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <strong>Новые выпуски:</strong>
            </div>
            <div class="panel-body">              
            
                <h3 class="page-header" style="margin-top: 10px">Последние добаввленные <small>Latest</small></h3>
                <div class="slick-crousel">
              {% for issue in last_issues %}
                
                 <div class="crousel_item">
                  <div class="thumbnail text-center" style="">
                  <a href="{% url 'novels:IssueDetail' slug=issue.slug %}">
                  {% for thumb in thumbnails %}
                      {% if thumb.issue == issue %}
                        <img class="img-rounded" style="width:160px; height:250px;" src="{{ thumb.get_abs_url }}" alt="">
                      {% endif %}
                    {% endfor %}
                      </a>                      
                          <strong><h4><span class="label label-default">Выпуск #{{ issue.number }}</span></h4></strong>                
                   </div>
                </div>              
    
              {% endfor %}
              </div>
            </div>
        </div>
        
        <div class="panel panel-default">
           <div class="panel-heading"><strong>Популярные издатели:</strong></div>
           <div class="panel-body">
               {% for publisher in top_pubs %}
                 <div class="col-xs-6 col-sm-3 col-md-3 col-lg-2">
                  <div class="thumbnail" style="height: 220px;">
                          <a href="{% url 'novels:PublisherDetail' publisher.slug %}"><img class="img-rounded" src="{{ publisher.imgUrl }}" style="width: 150px; height: 150px;" alt="{{ publisher.pub_title }} Picture"></a>
                      <div class="caption text-center">
                          <strong>{{ publisher.pub_title }}</strong>
                          <span class="label label-primary">{{ publisher.subs.count }}</span>
                    </div>
                  </div>
                  </div>
              {% endfor %}
           </div>
       </div>
    </div>
{% endblock %}

firstapp/novels/templates/novels/nav.html
{% load extra_tags %}
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'blog:list' %}">OPEN|Fridge</a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse">
            
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Категории<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                    {% get_list %}    
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Комиксы<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'novels:index' %}">Обновления</a></li>
                        <li><a href="{% url 'novels:PublisherList' %}">Издатели</a></li>
                        <li><a href="{% url 'novels:TitleList' %}">Серии</a></li>
                        <li><a href="{% url 'novels:ArcList' %}">События</a></li>
                        <li><a href="{% url 'novels:GroupList' %}">Команды</a></li>
                        <li><a href="{% url 'novels:CharList' %}">Персонажи</a></li>
                    </ul>
                </li>
            </ul>
        
        <form class="navbar-form navbar-right" role="search">
    
                    
                <div class="input-group">
                    <input type="text" class="form-control">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                    </span>
                </div>
        
        </form>            
        </div>
    </div>
</nav>

firstapp/novels/templates/novels/tit_detail.html
{% extends 'novels/base.html' %}
{% block jquery %}     
    $('#IssuePreview a').click(function (e) {
      e.preventDefault()
      $(this).tab('show')
    })
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
      <div class="container">
       <div class="panel panel-default">
               <div class="panel-heading">
                   <h4><strong>{{ title.title }}</strong> <small>{{ title.orig_title }}</small></h4>
                </div>
                <div class="panel-body">
                    <div class="col-lg-3 col-md-4 col-sm-5">
                           <div class="thumbnail"><img style="width:246px; height:380px;" src="{{ title.imgUrl }}" class="img-rounded" alt=""></div>                       
                    </div>
                    <div class="col-lg-9 col-md-8 col-sm-7">
                       <h4><strong>Описание серии:</strong></h4>
                        <p>{{ title.desc }}</p>
                        <div>
                            <table class="table table-striped">
                                  <caption><strong>Подробная информация о серии:</strong></caption>
                                  <tbody>
                                    <tr>
                                      <th scope="row">Жанр:</th>
                                      <td>{% for genre in title.genre.all %}{{ genre.name }}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
                                    </tr>
                                    {% if title.arc %}
                                       <tr>
                                       <th scope="row">Событие:</th>
                                           <td><a href="{% url 'novels:ArcDetail' title.arc.slug %}">{{ title.arc.arc_title }}</a></td>
                                      </tr> 
                                    {% endif %}
                                    <tr>
                                      <th scope="row">Издатель:</th>
                                      <td><a href="{% url 'novels:PublisherDetail' title.publisher.slug %}">{{ title.publisher.pub_title }}</a></td>
                                    </tr>
                                    <tr>
                                    <th scope="row">Перевод:</th>
                                      <td><a href="{{ title.translateURL }}">Сайт переводчика</a></td>
                                    </tr>
                                    <tr>
                                      <th scope="row">Сценарист:</th>
                                      <td>{{ title.author }}</td>
                                    </tr>
                                    <tr>
                                      <th scope="row">Художник:</th>
                                      <td>{{ title.artist }}</td>
                                    </tr>
                                    <tr>
                                      <th scope="row">Кол-во выпусков:</th>
                                      <td>{{ num_of_issue }}</td>
                                    </tr>
                                    <tr>
                                      <th scope="row">Статус:</th>
                                      <td>{{ title.status }}</td>
                                    </tr>
                                  </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="container-fluid">
                           <div class="bs-example bs-example-tabs">
                                <ul id="IssuePreview" class="nav nav-tabs nav-justified">
                                  <li class="active"><a href="#list" data-toggle="tab">Список</a></li>
                                  <li class=""><a href="#thumbnails" data-toggle="tab">Обложки</a></li>
                                </ul>
                                <hr>
                                <div id="IssuePreviewContent" class="tab-content">
                                  <div class="tab-pane fade active in" id="list">
                                    <ul class="list-group">
                                       {% for issue in issues %}
                                           <li class="list-group-item"><a href="{% url 'novels:IssueDetail' slug=issue.slug %}">
                                           <strong>{{ title.title }}:</strong> 
                                               #{{ issue.number }} {% if issue.trans_name %}{{ issue.trans_name }}{% endif %} / 
                                           <strong>{{ title.orig_title }}:</strong> 
                                               #{{ issue.number }} {% if issue.name %}{{ issue.name }}{% endif %}</a></li>
                                       {% endfor %}
                                    </ul>
                                  </div>
                                  <div class="tab-pane fade" id="thumbnails">
                                    <div class="panel panel-default">
                                        <div class="panel-body text-center">
                                            {% for thumb in thumbnails %}
                                            <a href="{% url 'novels:IssueDetail' slug=thumb.issue.slug %}"><img style="width:130px; height:200px;" src="{{ thumb.get_abs_url }}" class="img-rounded" alt=""></a>
                                            {% endfor %}
                                        </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            
                    </div>
                </div>
           </div>
       </div>
    </div>
</div>

{% endblock %}

firstapp/novels/templates/novels/tit_list.html
{% extends 'novels/base.html' %}
{% block content %}
<div class="container">
<div class="row">
    {% for title in object_list %}
    <div class="col-sm-6 col-md-6 col-lg-4" style="">
       <div class="panel panel-default">
       <div class="panel-heading text-center">
           <strong>{{ title.title }}</strong><br><small>{{ title.orig_title }}</small>
       </div>
       <div class="panel-body">
        <div class="media">
            <a class="pull-left" href="{% url 'novels:TitleDetail' title.slug %}">
                <img class="media-object img-rounded" style="width:130px; height:200px;" src="{{ title.imgUrl }}" alt="{{ title.title }} Pic">
            </a>
            <div class="media-body">
                <ul class="list-group">
                   <li class="list-object"><strong>Издатель:</strong><p>
                        <a href="{% url 'novels:PublisherDetail' title.publisher.slug %}">{{ title.publisher.pub_title }}</a>
                        </p>
                    </li>
                    <li class="list-object"><strong>Жанр:</strong><p>
                        {% for genre in title.genre.all %}{% if forloop.first %}{{ genre.name }}{% endif %}{% endfor %}
                        </p>
                    </li>
                    <li class="list-object"><strong>Статус:</strong><p>
                        {{ title.status }}
                        </p>
                    </li>
                </ul>
            </div>            
        </div>
        
        </div>
        <div class="panel-footer"><a href="{% url 'novels:TitleDetail' title.slug %}" class="btn btn-default text-center btn-block">Подробнее <i class="glyphicon glyphicon-menu-hamburger"></i></a></div>
        </div>
    </div>
    {% endfor %}
</div>
</div>
{% endblock %}